FROM python:3.9

WORKDIR /app

COPY abstract/ ./abstract/
ENV PYTHONPATH=/app

COPY poetry.lock /app/
COPY pyproject.toml /app/

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    pip install six && \
    poetry install --no-root

CMD ["python"]